<!DOCTYPE html>
<html lang="vn">
<head>
    <title>Gửi hàng toàn quốc</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" type="" href="/images/delivery-truck.png" />
    <link rel="stylesheet" href="/fonts/icomoon/style.css">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/magnific-popup.css">
    <link rel="stylesheet" href="/css/jquery-ui.css">
    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="/css/aos.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/base/base.css">
	<link href="/css/fontawesome-free-5.15.1-web/css/fontawesome.css" rel="stylesheet">
	<link href="/css/fontawesome-free-5.15.1-web/css/brands.css" rel="stylesheet">
	<link href="/css/fontawesome-free-5.15.1-web/css/solid.css" rel="stylesheet">
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/jquery-ui.js"></script>
    <script src="js/transport/common.js"></script>
	<script>
		$(document).ready(function(){
			$('#myModal').on('shown.bs.modal', function () {
				$('#video1')[0].currentTime = 0;
				$('#video1')[0].play();
			})
			$('#myModal').on('hidden.bs.modal', function () {
				$('#video1')[0].pause();
			})
		});
	</script>
</head>
<body>
    <div class="site-wrap">
        <header class="py-0 feature-3" role="banner">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-11 col-xl-2">
						<a href="index.html" class="text-white h2 mb-0"><img src="images/delivery-truck.png"/></a>
					</div>
                    <div class="x">
					<nav class="navbar navbar-expand-xl navbar-dark">
						<div class="y d-flex flex-wrap">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContentXL" aria-controls="navbarSupportedContentXL" aria-expanded="false" aria-label="Toggle navigation">
							    <span class="navbar-toggler-icon"></span>
						    </button>
						    <?php if($this->login): ?>
						    <div class="account-login">
							    <a class="nav-link" id="menu-1" href="#"><img class="rounded-circle" alt="100x100" width="23px" src="images/boy.png" data-holder-rendered="true"><span class="text-white">Nguyễn Quốc Đạt</span></a>
						    </div>
                        </div>	
						<?php endif;?>
						<div class="collapse navbar-collapse" id="navbarSupportedContentXL">
							<ul class="navbar-nav mr-auto site-menu">
								<li class="nav-item active">
									<a class="nav-link h4" href="#">Trang chủ</a>
								</li>
								<li class="nav-item">
									<a class="nav-link h4" href="#">Về chúng tôi</a>
								</li>
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle h4" href="#" id="navbarDropdownXL" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dịch vụ</a>
									<div class="dropdown-menu" aria-labelledby="navbarDropdownXL">
										<a class="dropdown-item" href="#">Vận chuyển 24/7</a>
										<a class="dropdown-item" href="#">Vận chuyển ...</a>
										<a class="dropdown-item" href="#">....</a>
									</div>
								</li>
								<li class="nav-item">
									<a class="nav-link h4" href="#">Blog</a>
								</li>
								<li class="nav-item">
									<a class="nav-link h4" id="menu-1" href="#">Quy trình giao nhận</a>
								</li>
								<li class="nav-item">
									<a class="nav-link h4" href="#">Contact</a>
								</li>
								</li>
								<?php if(!$this->login): ?>
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle h4" href="#" id="navbarDropdownXL" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tài khoản</a>
									<div class="dropdown-menu" aria-labelledby="navbarDropdownXL">
										<a class="dropdown-item" href="javascript:void(0);" id="login"><i class="fas fa-sign-in-alt"></i>&nbsp;Đăng nhập</a>
										<a class="dropdown-item" href="#"><i class="fas fa-edit"></i>&nbsp;Đăng ký</a>
										<a class="dropdown-item" href="#"><i class="fas fa-key"></i>&nbsp;Quên thông tin đăng nhập</a>
									</div>
								</li>
								<?php endif;?>
							</ul>
						</div>
					</nav>
                    </div>
				</div>
			</div>
		</header>
    </div>
    <div class="site-blocks-cover overlay" style="background-image: url(images/bg.jpg);" data-aos="fade">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center">
                <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
                    <h1 class="text-warning font-weight-light mb-5 text-uppercase font-weight-bold">Dịch vụ vận chuyển hàng hóa liên tỉnh</h1>
                    <p><a href="#" class="btn btn-primary py-3 px-5 text-white">Tạo đơn hàng</a></p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row align-items-center no-gutters align-items-stretch overlap-section">
            <div class="col-md-12 col-12 col-lg-4">
                <div class="feature-1 pricing h-100 text-center">
                    <div class="icon">
                        <span class="icon-dollar"></span>
                    </div>
                    <h2 class="my-4 heading">Giá tốt nhất</h2>
                    <p>Chúng tôi cam kết về giá cả tốt nhất theo từng đơn hàng mà khách hàng gửi đi.</p>
                </div>
            </div>
            <div class="col-md-12 col-12 col-lg-4">
                <div class="free-quote bg-dark h-100">
                    <h2 class="my-4 heading text-center">Nhận báo giá miển phí</h2>
                    <form method="post">
                        <div class="form-group">
                            <label for="fq_name">Tên</label>
                            <input type="text" class="form-control btn-block" id="fq_name" name="fq_name" placeholder="Nhập họ và tên của bạn">
                        </div>
                        <div class="form-group mb-4">
                            <label for="fq_email">Email</label>
                            <input type="text" class="form-control btn-block" id="fq_email" name="fq_email" placeholder="Nhập địa chỉ email">
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary text-white py-2 px-4 btn-block" value="Nhận báo giá">
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-12 col-12 col-lg-4">
                <div class="feature-3 pricing h-100 text-center">
                    <div class="icon">
                        <span class="icon-phone"></span>
                    </div>
                    <h2 class="my-4 heading">Hổ trợ 24/7</h2>
                    <p>Vui lòng liên hệ hotline: 199999 (miễn phí) để được hổ trợ.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="site-section">
        <div class="container" id="quytrinh">
			<div class="procedure-view">
				<div class="row justify-content-center mb-5">
					<div class="col-md-7 text-center border-primary">
						<h2 class="mb-0 text-primary">Quy trình giao nhận</h2>
					</div>
				</div>
				<div class="row justify-content-center mb-5">
					<div id="animate-description" class="mb-1 text-center justify-content-center">Bước - 1</div>
				</div>
			</div>
			<div class="procedure-road">
				<div id="animate">
					<span class="procedure-road-bike movebike"></span>
				</div>
			</div>
			<div id="step">
				<div id="step1" class="pn-circle active">Bước<br>01</div>
				<div class="pn-line"></div>
				<div id="step2" class="pn-circle">Bước<br>02</div>
				<div class="pn-line"></div>
				<div id="step3" class="pn-circle">Bước<br>03</div>
				<div class="pn-line"></div>
				<div id="step4" class="pn-circle">Bước<br>04</div>
				<div class="pn-line-end"></div>
			</div>
        </div>
    </div>
    <div class="site-section block-13">
        <!-- <div class="container"></div> -->
		<div class="row justify-content-center ml-0 mr-0 mb-3">
			<div class="col-md-7 text-center border-primary">
				<h2 class="mb-0 text-primary">Hệ thống kho</h2>
			</div>
		</div>
        <div class="owl-carousel nonloop-block-13">
            <div>
                <a href="#" class="unit-1 text-center">
                    <img src="images/img_1.jpg" alt="Image" class="img-fluid">
                    <div class="unit-1-text">
                        <h3 class="unit-1-heading">Kho 1</h3>
                        <p class="px-5">Chi tiết</p>
                    </div>
                </a>
            </div>
            <div>
                <a href="#" class="unit-1 text-center">
                    <img src="images/img_5.jpg" alt="Image" class="img-fluid">
                    <div class="unit-1-text">
                        <h3 class="unit-1-heading">Kho 2</h3>
                        <p class="px-5">Chi tiết</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="site-section bg-light">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <div class="col-md-7 text-center border-primary">
                    <h2 class="font-weight-light text-primary">CÁC DỊCH VỤ KHÁC</h2>
                    <p class="color-black-opacity-5">Chúng tôi cung cấp các dịch vụ sau</p>
                </div>
            </div>
            <div class="row align-items-stretch">
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
                    <div class="unit-4 d-flex">
                        <div class="unit-4-icon mr-4"><span class="text-primary flaticon-travel"></span></div>
                        <div>
                            <h3>Vận tải hàng không</h3>
                            <p>xxxxxxxxxxxxxxxxxxxxxxx.</p>
                            <p><a href="#">Tìm hiểu thêm</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
                    <div class="unit-4 d-flex">
                        <div class="unit-4-icon mr-4"><span class="text-primary flaticon-sea-ship-with-containers"></span></div>
                        <div>
                            <h3>Vận tải đường biển</h3>x
                            <p>xxxxxxxxxxxxx.</p>
                            <p><a href="#">Tìm hiểu thêm</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
                    <div class="unit-4 d-flex">
                        <div class="unit-4-icon mr-4"><span class="text-primary flaticon-frontal-truck"></span></div>
                        <div>
                            <h3>Vận chuyển mặt đất</h3>
                            <p>xxxxxxxxxxxxx.</p>
                            <p><a href="#">Tìm hiểu thêm</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
                    <div class="unit-4 d-flex">
                        <div class="unit-4-icon mr-4"><span class="text-primary flaticon-barn"></span></div>
                        <div>
                            <h3>Kho bãi</h3>
                            <p>xxxxxxxxxx.</p>
                            <p><a href="#">Tìm hiểu thêm</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
                    <div class="unit-4 d-flex">
                        <div class="unit-4-icon mr-4"><span class="text-primary flaticon-car"></span></div>
                        <div>
                            <h3>Xe giao hàng</h3>
                            <p>xxxxxxxxxxxxxxxxxxxxx.</p>
                            <p><a href="#">Tìm hiểu thêm</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="site-blocks-cover overlay inner-page-cover" style="background-image: url(images/hero_bg_2.jpg); background-attachment: fixed;">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center">
                <div class="col-md-7" data-aos="fade-up" data-aos-delay="400">
                    <a data-toggle="modal" data-target="#myModal" class="btn play-single-big mb-4 d-inline-block"><span class="icon-play"></span></a>
                    <h2 class="text-white font-weight-light mb-5 h1">Xem dịch vụ của chúng tôi bằng cách xem video ngắn này</h2>
                </div>	
            </div>
        </div>
		<!-- Modal -->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog" role="document">
			<div class="modal-content">
			  <div class="modal-header">
				<h4 id="myModalLabel" class="modal-title font-weight-light text-primary">Dịch vụ của chúng tôi</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  </div>
			  <div class="modal-body">
				<video controls id="video1" style="width: 100%; height: auto; margin:0 auto; frameborder:0;">
				  <source src="images/video.mp4" type="video/mp4">
				  Your browser doesn't support HTML5 video tag.
				</video>
			  </div>
			</div>
		  </div>
		</div>
    </div>
    <div class="site-section border-bottom">
        <div class="container">

            <div class="row justify-content-center mb-5">
                <div class="col-md-7 text-center border-primary">
                    <h2 class="font-weight-light text-primary">Góp ý</h2>
                </div>
            </div>
            <div class="slide-one-item home-slider owl-carousel">
                <div>
                    <div class="testimonial">
                        <figure class="mb-4">
                            <img src="images/boy.png" alt="Image" class="img-fluid mb-3">
                            <p>NQĐ</p>
                        </figure>
                        <blockquote>
                            <p>&ldquo;Chất lượng.&rdquo;</p>
                        </blockquote>
                    </div>
                </div>
                <div>
                    <div class="testimonial">
                        <figure class="mb-4">
                            <img src="images/boy.png" alt="Image" class="img-fluid mb-3">
                            <p>VAT</p>
                        </figure>
                        <blockquote>
                            <p>&ldquo;Giá cả.&rdquo;</p>
                        </blockquote>
                    </div>
                </div>
                <div>
                    <div class="testimonial">
                        <figure class="mb-4">
                            <img src="images/boy.png" alt="Image" class="img-fluid mb-3">
                            <p>NTT</p>
                        </figure>
                        <blockquote>
                            <p>&ldquo;Nhân viên.&rdquo;</p>
                        </blockquote>
                    </div>
                </div>
                <div>
                    <div class="testimonial">
                        <figure class="mb-4">
                            <img src="images/boy.png" alt="Image" class="img-fluid mb-3">
                            <p>TTN</p>
                        </figure>
                        <blockquote>
                            <p>&ldquo;Thời gian.&rdquo;</p>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="site-section">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <div class="col-md-7 text-center border-primary">
                    <h2 class="font-weight-light text-primary">BLOG CỦA CHÚNG TÔI</h2>
                    <p class="color-black-opacity-5">Xem tin tức và cập nhật hàng ngày của chúng tôi</p>
                </div>
            </div>
        </div>
    </div>
    <div class="site-section border-top">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h2 class="mb-5 text-black">Hãy thử dịch vụ của chúng tôi</h2>
                    <p class="mb-0"><a href="booking.html" class="btn btn-primary py-3 px-5 text-white">Tạo đơn hàng</a></p>
                </div>
            </div>
        </div>
    </div>
    <footer class="site-footer" style="padding:1em 0">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-3">
                            <h2 class="footer-heading mb-4">Quick Links</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </div>
                        <div class="col-md-3">
                            <h2 class="footer-heading mb-4">Products</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </div>
                        <div class="col-md-3">
                            <h2 class="footer-heading mb-4">Features</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </div>
                        <div class="col-md-3">
                            <h2 class="footer-heading mb-4">Follow Us</h2>
                            <a href="#" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
                            <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
                            <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                            <a href="#" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <h2 class="footer-heading mb-4">Subscribe Newsletter</h2>
                    <form action="#" method="post">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control border-secondary text-white bg-transparent" placeholder="Enter Email" aria-label="Enter Email" aria-describedby="button-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary text-white" type="button" id="button-addon2">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <div class="border-top pt-5">
                        <p>Copyright &copy;</p>
                    </div>
                </div>

            </div>
        </div>
    </footer>
	<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header border-bottom-0">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					  <span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-title text-center">
						<h4>Đăng nhập</h4>
					</div>
					<div class="d-flex flex-column text-center">
						<form>
							<div class="form-group">
								<input type="email" class="form-control" id="email1"placeholder="Địa chỉ email của bạn...">
							</div>
							<div class="form-group">
							  <input type="password" class="form-control" id="password1" placeholder="Mật khẩu...">
							</div>
							<button type="button" class="btn btn-info btn-block btn-round">Đăng nhập</button>
						</form>
						<div class="text-center text-muted delimiter">Hoặc</div>
						<div class="d-flex justify-content-center social-buttons">
							<button type="button" class="btn btn-secondary btn-round" data-toggle="tooltip" data-placement="top" title="Twitter">
								<i class="fab fa-twitter"></i>
							</button>
							<button type="button" class="btn btn-secondary btn-round" data-toggle="tooltip" data-placement="top" title="Facebook">
								<i class="fab fa-facebook"></i>
							</button>
							<button type="button" class="btn btn-secondary btn-round" data-toggle="tooltip" data-placement="top" title="Linkedin">
								<i class="fab fa-linkedin"></i>
							</button>
						</div>
					</div>
				</div>
			<div class="modal-footer d-flex justify-content-center">
				<div class="signup-section">Bạn chưa phải là thành viên?<a href="#a" class="text-info"> Đăng ký.</a></div>
			</div>
		</div>
	</div>
    <script src="js/jquery-migrate-3.0.1.min.js"></script>
    <script src="js/jquery-ui.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.stellar.min.js"></script>
    <script src="js/jquery.countdown.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/bootstrap-datepicker.min.js"></script>
    <script src="js/aos.js"></script>
    <script src="js/main.js"></script>
</body>
</html>