<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="" href="/img/student.ico" />
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/jquery-3.5.1.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <title>Web</title>
    <script>
        $(function(){
            var vid = document.getElementById('video-intro');
            vid.currentTime = 8;
        });
    </script> 
	
    <script src="public/js/transports/common.js"></script>
</head>
<body>
    <div id="main">
        <div class="header">
            <div class="css-header">
                <div class="logo">
                    <img id="logo-page" src="/img/student.png" onclick="window.location.href='/';"/>    
                </div>
                <div class="nav-cs">
                    <nav class="navbar navbar-expand-sm">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="/">Trang Chủ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#section-1">Tham khảo</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Liên hệ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Khóa học</a>
                            </li>
                            <li class="nav-item">
                                <button id="btn-login" type="button" class="button-started" data-toggle="modal" data-target="#exampleModal">Đăng nhập</button>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="content-welcome">
                <div class="login-area">
                    <p class="title">MÔN TIN HỌC</p>
                    <div class="button-login-area">
                        <div class="login-st-le-ad">
                            <img src="/img/student-login.png" onclick="window.location.href='/learninformaticsonline/login/student';"/>
                            <p>Học Sinh</p>
                        </div>
                        <div class="login-st-le-ad">
                            <img  src="/img/parent-login.png" onclick="window.location.href='/learninformaticsonline/login/parent';"/>
                            <p>Phụ Huynh</p>
                        </div>
                        <div class="login-st-le-ad">
                            <img src="/img/admin-login.png" onclick="window.location.href='/learninformaticsonline/login/admin';"/>
                            <p>Quản trị viên</p>
                        </div>
                    </div>
                </div>
                <div class="video-intro">
                    <video id="video-intro" class="video-play" type="video/mp4" width="85%" height="100%" src="/img/clip-intro.mp4" autoplay></video>
                </div>
            </div>
            <div class="section-1" id="section-1">
                <div class="section-1-part">
                    <div class="section-1-content">
                        <div class="section-1-title">
                            <p class="section-1-text">Trong thời đại công nghiệp 4.0 việc học trực tuyến qua mạng rất phát triển, vì thế ở bộ môn tin học tại trường tiểu học phát triển website hổ trợ học sinh học thêm ở nhà. Đồng thời kết hợp sự giám sát của phụ huynh thông qua website</p>
                        </div>
                        <div class="section-1-detail">
                            <div class="detail">
                                <div class="div-img">
                                    <img src="/img/top-asset-1@2x.png"/>
                                </div>
                                <p class="css-text">Có thể học bất kỳ đâu</p>
                                <p class="css-sub-text">Các con có thể học bất kỳ nơi nào, đồng thời các phụ huynh có thể theo dõi tình trạng học tập</p>
                            </div>
                            <div class="detail">
                                <div class="div-img">
                                    <img src="/img/top-asset-2@2x.png"/>
                                </div>
                                <p class="css-text">Đơn giản, vui chơi, giải trí</p>
                                <p class="css-sub-text">Kết hợp được vừa học vừa chơi vào trong các bài học giúp giảm sự nhàm chán trong việc học</p>
                            </div>
                            <div class="detail">
                                <div class="div-img">
                                    <img src="/img/top-asset-3@2x.png"/>
                                </div>
                                <p class="css-text">Để lại những thắc mắc</p>
                                <p class="css-sub-text">Có những vấn đề các con và phụ huynh không hiểu về hệ thông có thể trực tiếp gửi phản hồi</p>
                            </div>
                        </div>
                    </div>
                    <div class="sub-footer">
                        <p>Các con hãy bắt đầu những bài học thú vị nào ... </p>
                        <div>
                            <button type="button" class="button-started" data-toggle="modal" data-target="#exampleModal">Bắt đầu ngay →</button>
                        </div>
                        <img src="/img/hacker.png"/>
                        <img src="/img/hardware.png"/>
                        <img src="/img/programmer.png"/>
                    </div>
                </div>
            </div>
        </div>
        <footer>
           <div class="div-footer">
                <div>
                    <h4>Trường</h4>
                    <ul>
                        <li>Tiểu học</li>
                    </ul>
                </div>
                <div>
                    <h4>Giáo viên</h4>
                    <ul>
                        <li>Giáo viên A</li>
                    </ul>
                </div>
                <div>
                    <h4>Lớp</h4>
                    <ul>
                        <li>Lớp 3</li>
                        <li>Lớp 4</li>
                        <li>Lớp 5</li>
                    </ul>
                </div>
           </div>
           <p>Môn tin học</p>
        </footer>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title">Đăng nhập</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <div class="modal-login">
                        <div class="button-login-area">
                            <div class="login-st-le-ad">
                                <img src="/img/student-login.png" onclick="window.location.href='/learninformaticsonline/login/student';"/>
                                <p>Học Sinh</p>
                            </div>
                            <div class="login-st-le-ad">
                                <img  src="/img/parent-login.png" onclick="window.location.href='/learninformaticsonline/login/parent';"/>
                                <p>Phụ Huynh</p>
                            </div>
                            <div class="login-st-le-ad">
                                <img src="/img/admin-login.png" onclick="window.location.href='/learninformaticsonline/login/admin';"/>
                                <p>Quản trị viên</p>
                            </div>
                        </div>
                    </div>  
                </div>
            </div>
        </div>
    </div>
</body>
</html>